/*
Equipe: OLLI PET

Andr� Rosa Colombo - RM563112
Gabriely Bonfim Silva - RM566242
Henrique Rodrigues Vespasiano - RM562917
Mirelly Sousa Alves - RM566299
Ruan Luca Feliciano - RM562218
*/

SET SERVEROUTPUT ON
SET VERIFY OFF

-- DROPS
DROP TABLE AUDITORIA_PRONTUARIO CASCADE CONSTRAINTS;
DROP TABLE LOG_ERRO CASCADE CONSTRAINTS;
DROP TABLE APLICACAO_VACINA CASCADE CONSTRAINTS;
DROP TABLE VACINA CASCADE CONSTRAINTS;
DROP TABLE TRATAMENTO CASCADE CONSTRAINTS;
DROP TABLE CONSULTA CASCADE CONSTRAINTS;
DROP TABLE PRONTUARIO CASCADE CONSTRAINTS;
DROP TABLE PET CASCADE CONSTRAINTS;
DROP TABLE MED_VET CASCADE CONSTRAINTS;
DROP TABLE RESPONSAVEL CASCADE CONSTRAINTS;

-- TABELAS
CREATE TABLE LOG_ERRO(
    ID_LOG NUMBER PRIMARY KEY,
    NOME_PROCEDURE VARCHAR2(100),
    USUARIO_DB VARCHAR2(100),
    DATA_ERRO DATE,
    CODIGO_ERRO NUMBER,
    MSG_ERRO VARCHAR2(4000)
);

CREATE TABLE RESPONSAVEL(
    ID_RESP NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASC DATE,
    CPF VARCHAR2(11) UNIQUE,
    EMAIL VARCHAR2(100)
);

CREATE TABLE MED_VET(
    ID_MED_VET NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CRMV VARCHAR2(20) UNIQUE,
    ESPECIALIDADE VARCHAR2(80),
    EMAIL VARCHAR2(100)
);

CREATE TABLE PET(
    ID_PET NUMBER PRIMARY KEY,
    NOME VARCHAR2(80) NOT NULL,
    DESCRICAO VARCHAR2(255),
    RACA VARCHAR2(80) NOT NULL,
    ESPECIE VARCHAR2(20) NOT NULL,
    DATA_NASC DATE NOT NULL,
    ID_RESP NUMBER NOT NULL,
    CONSTRAINT FK_PET_RESP FOREIGN KEY(ID_RESP) REFERENCES RESPONSAVEL(ID_RESP)
);

CREATE TABLE CONSULTA(
    ID_CONSULTA NUMBER PRIMARY KEY,
    ID_PET NUMBER NOT NULL,
    ID_MED_VET NUMBER NOT NULL,
    DATA_HORA DATE NOT NULL,
    MOTIVO VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    OBSERVACOES VARCHAR2(500),
    CONSTRAINT FK_CONSULTA_PET FOREIGN KEY(ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT FK_CONSULTA_VET FOREIGN KEY(ID_MED_VET) REFERENCES MED_VET(ID_MED_VET)
);

CREATE TABLE PRONTUARIO(
    ID_PRONTUARIO NUMBER PRIMARY KEY,
    ID_PET NUMBER NOT NULL,
    ID_MED_VET NUMBER NOT NULL,
    ID_CONSULTA NUMBER,
    PROCEDIMENTO VARCHAR2(255) NOT NULL,
    DATA_PROCEDIMENTO DATE NOT NULL,
    LOCAL_ATENDIMENTO VARCHAR2(120) NOT NULL,
    OBSERVACAO VARCHAR2(500),
    CONSTRAINT FK_PRONT_PET FOREIGN KEY(ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT FK_PRONT_VET FOREIGN KEY(ID_MED_VET) REFERENCES MED_VET(ID_MED_VET),
    CONSTRAINT FK_PRONT_CONSULTA FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA),
    CONSTRAINT UK_PRONT_CONSULTA UNIQUE(ID_CONSULTA)
);

CREATE TABLE VACINA(
    ID_VACINA NUMBER PRIMARY KEY,
    NOME VARCHAR2(80) NOT NULL,
    ESPECIE VARCHAR2(20) NOT NULL,
    DOSES_PROTOCOLO NUMBER NOT NULL,
    INTERVALO_DIAS NUMBER NOT NULL,
    MESES_REFORCO NUMBER,
    CONSTRAINT UK_VACINA_NOME_ESPECIE UNIQUE(NOME, ESPECIE)
);

CREATE TABLE APLICACAO_VACINA(
    ID_APLICACAO NUMBER PRIMARY KEY,
    ID_PET NUMBER NOT NULL,
    ID_VACINA NUMBER NOT NULL,
    ID_MED_VET NUMBER NOT NULL,
    NUMERO_DOSE NUMBER NOT NULL,
    DATA_APLICACAO DATE NOT NULL,
    PROXIMA_DOSE DATE,
    LOTE VARCHAR2(40),
    CONSTRAINT FK_APLIC_PET FOREIGN KEY(ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT FK_APLIC_VACINA FOREIGN KEY(ID_VACINA) REFERENCES VACINA(ID_VACINA),
    CONSTRAINT FK_APLIC_VET FOREIGN KEY(ID_MED_VET) REFERENCES MED_VET(ID_MED_VET),
    CONSTRAINT UK_APLIC_DOSE UNIQUE(ID_PET, ID_VACINA, NUMERO_DOSE)
);

CREATE TABLE TRATAMENTO(
    ID_TRATAMENTO NUMBER PRIMARY KEY,
    ID_PET NUMBER NOT NULL,
    ID_MED_VET NUMBER NOT NULL,
    ID_CONSULTA NUMBER,
    MEDICAMENTO VARCHAR2(120) NOT NULL,
    DOSAGEM VARCHAR2(80) NOT NULL,
    INTERVALO_HORAS NUMBER NOT NULL,
    DURACAO_DIAS NUMBER NOT NULL,
    INICIO_EM DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    OBSERVACOES VARCHAR2(500),
    CONSTRAINT FK_TRAT_PET FOREIGN KEY(ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT FK_TRAT_VET FOREIGN KEY(ID_MED_VET) REFERENCES MED_VET(ID_MED_VET),
    CONSTRAINT FK_TRAT_CONSULTA FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

CREATE TABLE AUDITORIA_PRONTUARIO(
    ID_AUDITORIA NUMBER PRIMARY KEY,
    USUARIO_DB VARCHAR2(100),
    OPERACAO VARCHAR2(10),
    DATA_HORA DATE,
    ID_PRONTUARIO_ANTERIOR NUMBER,
    ID_PET_ANTERIOR NUMBER,
    ID_MED_VET_ANTERIOR NUMBER,
    ID_CONSULTA_ANTERIOR NUMBER,
    PROCEDIMENTO_ANTERIOR VARCHAR2(255),
    DATA_PROCEDIMENTO_ANTERIOR DATE,
    LOCAL_ANTERIOR VARCHAR2(120),
    ID_PRONTUARIO_NOVO NUMBER,
    ID_PET_NOVO NUMBER,
    ID_MED_VET_NOVO NUMBER,
    ID_CONSULTA_NOVO NUMBER,
    PROCEDIMENTO_NOVO VARCHAR2(255),
    DATA_PROCEDIMENTO_NOVO DATE,
    LOCAL_NOVO VARCHAR2(120)
);

-- PROCEDURE DE LOG
CREATE OR REPLACE PROCEDURE P_LOG_ERRO(
    P_NOME_PROCEDURE IN VARCHAR2,
    P_CODIGO_ERRO IN NUMBER,
    P_MSG_ERRO IN VARCHAR2
)
IS
    V_ID NUMBER;
BEGIN
    SELECT NVL(MAX(ID_LOG), 0) + 1 INTO V_ID FROM LOG_ERRO;

    INSERT INTO LOG_ERRO(
        ID_LOG, NOME_PROCEDURE, USUARIO_DB, DATA_ERRO, CODIGO_ERRO, MSG_ERRO
    )
    VALUES(
        V_ID, P_NOME_PROCEDURE, USER, SYSDATE, P_CODIGO_ERRO, P_MSG_ERRO
    );
END P_LOG_ERRO;
/

-- PROCEDURES DE CARGA
CREATE OR REPLACE PROCEDURE P_INS_RESP(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_DATA DATE,
    P_CPF VARCHAR2,
    P_EMAIL VARCHAR2
)
IS
BEGIN
    INSERT INTO RESPONSAVEL VALUES(P_ID, P_NOME, P_DATA, P_CPF, P_EMAIL);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, SQLERRM);
END P_INS_RESP;
/

CREATE OR REPLACE PROCEDURE P_INS_VET(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_CRMV VARCHAR2,
    P_ESPECIALIDADE VARCHAR2,
    P_EMAIL VARCHAR2
)
IS
BEGIN
    INSERT INTO MED_VET VALUES(P_ID, P_NOME, P_CRMV, P_ESPECIALIDADE, P_EMAIL);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, SQLERRM);
END P_INS_VET;
/

CREATE OR REPLACE PROCEDURE P_INS_PET(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_DESCRICAO VARCHAR2,
    P_RACA VARCHAR2,
    P_ESPECIE VARCHAR2,
    P_DATA DATE,
    P_RESP NUMBER
)
IS
BEGIN
    INSERT INTO PET VALUES(P_ID, P_NOME, P_DESCRICAO, P_RACA, P_ESPECIE, P_DATA, P_RESP);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, SQLERRM);
END P_INS_PET;
/

CREATE OR REPLACE PROCEDURE P_INS_CONSULTA(
    P_ID NUMBER,
    P_PET NUMBER,
    P_VET NUMBER,
    P_DATA DATE,
    P_MOTIVO VARCHAR2,
    P_STATUS VARCHAR2,
    P_OBSERVACOES VARCHAR2
)
IS
BEGIN
    INSERT INTO CONSULTA VALUES(P_ID, P_PET, P_VET, P_DATA, P_MOTIVO, P_STATUS, P_OBSERVACOES);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_CONSULTA', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_CONSULTA', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_CONSULTA', SQLCODE, SQLERRM);
END P_INS_CONSULTA;
/

CREATE OR REPLACE PROCEDURE P_INS_PRONTUARIO(
    P_ID NUMBER,
    P_PET NUMBER,
    P_VET NUMBER,
    P_CONSULTA NUMBER,
    P_PROCEDIMENTO VARCHAR2,
    P_DATA DATE,
    P_LOCAL VARCHAR2,
    P_OBSERVACAO VARCHAR2
)
IS
BEGIN
    INSERT INTO PRONTUARIO VALUES(
        P_ID, P_PET, P_VET, P_CONSULTA, P_PROCEDIMENTO, P_DATA, P_LOCAL, P_OBSERVACAO
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, SQLERRM);
END P_INS_PRONTUARIO;
/

CREATE OR REPLACE PROCEDURE P_INS_VACINA(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_ESPECIE VARCHAR2,
    P_DOSES NUMBER,
    P_INTERVALO NUMBER,
    P_REFORCO NUMBER
)
IS
BEGIN
    INSERT INTO VACINA VALUES(P_ID, P_NOME, P_ESPECIE, P_DOSES, P_INTERVALO, P_REFORCO);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_VACINA', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_VACINA', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_VACINA', SQLCODE, SQLERRM);
END P_INS_VACINA;
/

CREATE OR REPLACE PROCEDURE P_INS_APLICACAO(
    P_ID NUMBER,
    P_PET NUMBER,
    P_VACINA NUMBER,
    P_VET NUMBER,
    P_DOSE NUMBER,
    P_DATA DATE,
    P_PROXIMA DATE,
    P_LOTE VARCHAR2
)
IS
BEGIN
    INSERT INTO APLICACAO_VACINA VALUES(
        P_ID, P_PET, P_VACINA, P_VET, P_DOSE, P_DATA, P_PROXIMA, P_LOTE
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_APLICACAO', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_APLICACAO', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_APLICACAO', SQLCODE, SQLERRM);
END P_INS_APLICACAO;
/

CREATE OR REPLACE PROCEDURE P_INS_TRATAMENTO(
    P_ID NUMBER,
    P_PET NUMBER,
    P_VET NUMBER,
    P_CONSULTA NUMBER,
    P_MEDICAMENTO VARCHAR2,
    P_DOSAGEM VARCHAR2,
    P_INTERVALO NUMBER,
    P_DURACAO NUMBER,
    P_INICIO DATE,
    P_STATUS VARCHAR2,
    P_OBSERVACOES VARCHAR2
)
IS
BEGIN
    INSERT INTO TRATAMENTO VALUES(
        P_ID, P_PET, P_VET, P_CONSULTA, P_MEDICAMENTO, P_DOSAGEM,
        P_INTERVALO, P_DURACAO, P_INICIO, P_STATUS, P_OBSERVACOES
    );
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_TRATAMENTO', SQLCODE, 'DADO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_TRATAMENTO', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_TRATAMENTO', SQLCODE, SQLERRM);
END P_INS_TRATAMENTO;
/

-- CARGA
BEGIN
    P_INS_RESP(1, 'Carlos Silva', DATE '1985-05-10', '11111111111', 'carlos@gmail.com');
    P_INS_RESP(2, 'Mariana Souza', DATE '1990-08-15', '22222222222', 'mariana@gmail.com');
    P_INS_RESP(3, 'Rafael Lima', DATE '1982-02-20', '33333333333', 'rafael@gmail.com');
    P_INS_RESP(4, 'Juliana Alves', DATE '1995-11-03', '44444444444', 'juliana@gmail.com');
    P_INS_RESP(5, 'Fernanda Costa', DATE '1988-06-18', '55555555555', 'fernanda@gmail.com');

    P_INS_VET(1, 'Joao Mendes', 'CRMV001', 'Clinica geral', 'joao@olli.com');
    P_INS_VET(2, 'Ana Martins', 'CRMV002', 'Dermatologia', 'ana@olli.com');
    P_INS_VET(3, 'Bruno Santos', 'CRMV003', 'Cirurgia', 'bruno@olli.com');
    P_INS_VET(4, 'Camila Rocha', 'CRMV004', 'Felinos', 'camila@olli.com');
    P_INS_VET(5, 'Lucas Oliveira', 'CRMV005', 'Preventivo', 'lucas@olli.com');

    P_INS_PET(1, 'Rex', 'Agitado e brincalhao', 'Labrador', 'CAO', DATE '2020-01-10', 1);
    P_INS_PET(2, 'Mia', 'Calma e tranquila', 'Siames', 'GATO', DATE '2021-03-15', 2);
    P_INS_PET(3, 'Thor', 'Muito ativo', 'Golden Retriever', 'CAO', DATE '2019-07-22', 3);
    P_INS_PET(4, 'Luna', 'Docil', 'Persa', 'GATO', DATE '2022-09-05', 4);
    P_INS_PET(5, 'Nina', 'Carinhosa', 'Beagle', 'CAO', DATE '2023-02-12', 5);

    P_INS_CONSULTA(1, 1, 1, DATE '2026-08-10', 'Check-up', 'REALIZADA', 'Consulta preventiva');
    P_INS_CONSULTA(2, 2, 2, DATE '2026-08-12', 'Pele', 'REALIZADA', 'Avaliacao dermatologica');
    P_INS_CONSULTA(3, 3, 3, DATE '2026-08-15', 'Dor', 'REALIZADA', 'Avaliacao clinica');
    P_INS_CONSULTA(4, 4, 4, DATE '2026-08-18', 'Vacina', 'REALIZADA', 'Aplicacao de vacina');
    P_INS_CONSULTA(5, 5, 5, DATE '2026-08-20', 'Rotina', 'AGENDADA', 'Retorno preventivo');

    P_INS_PRONTUARIO(1, 1, 1, 1, 'Check-up', DATE '2026-08-10', 'Sala 1', 'Animal saudavel');
    P_INS_PRONTUARIO(2, 2, 2, 2, 'Consulta dermatologica', DATE '2026-08-12', 'Sala 2', 'Alergia leve');
    P_INS_PRONTUARIO(3, 3, 3, 3, 'Avaliacao clinica', DATE '2026-08-15', 'Sala 1', 'Dor muscular');
    P_INS_PRONTUARIO(4, 4, 4, 4, 'Vacina', DATE '2026-08-18', 'Sala 3', 'Sem reacoes');
    P_INS_PRONTUARIO(5, 5, 5, 5, 'Retorno preventivo', DATE '2026-08-20', 'Sala 2', 'Acompanhamento');

    P_INS_VACINA(1, 'V10', 'CAO', 3, 21, 12);
    P_INS_VACINA(2, 'Antirrabica', 'CAO', 1, 0, 12);
    P_INS_VACINA(3, 'V4', 'GATO', 3, 21, 12);
    P_INS_VACINA(4, 'Antirrabica', 'GATO', 1, 0, 12);
    P_INS_VACINA(5, 'Giardia', 'CAO', 2, 30, 12);

    P_INS_APLICACAO(1, 1, 1, 1, 1, DATE '2026-08-10', DATE '2026-09-10', 'L001');
    P_INS_APLICACAO(2, 2, 3, 2, 1, DATE '2026-08-12', DATE '2026-09-12', 'L002');
    P_INS_APLICACAO(3, 3, 1, 3, 2, DATE '2026-09-01', DATE '2027-08-01', 'L003');
    P_INS_APLICACAO(4, 4, 4, 4, 1, DATE '2026-08-18', DATE '2027-08-18', 'L004');
    P_INS_APLICACAO(5, 5, 5, 5, 1, DATE '2026-08-20', DATE '2026-09-20', 'L005');

    P_INS_TRATAMENTO(1, 1, 1, 1, 'Amoxicilina', '250mg', 12, 7, DATE '2026-08-10', 'ATIVO', 'Administrar apos alimentacao');
    P_INS_TRATAMENTO(2, 1, 1, 1, 'Dipirona', '10 gotas', 8, 3, DATE '2026-08-10', 'ENCERRADO', 'Controle de dor');
    P_INS_TRATAMENTO(3, 2, 2, 2, 'Shampoo', 'Uso topico', 24, 14, DATE '2026-08-12', 'ATIVO', 'Banho medicamentoso');
    P_INS_TRATAMENTO(4, 3, 3, 3, 'Anti-inflamatorio', '1 comprimido', 12, 5, DATE '2026-08-15', 'ATIVO', 'Repouso');
    P_INS_TRATAMENTO(5, 4, 4, 4, 'Suplemento', '5ml', 24, 10, DATE '2026-08-18', 'ATIVO', 'Uso diario');
    P_INS_TRATAMENTO(6, 2, 2, 2, 'Antialergico', '1 comprimido', 12, 4, DATE '2026-08-12', 'ENCERRADO', 'Tratamento concluido');
    P_INS_TRATAMENTO(7, 3, 3, 3, 'Analgesico', '5ml', 8, 6, DATE '2026-08-15', 'ENCERRADO', 'Controle da dor');
    P_INS_TRATAMENTO(8, 4, 4, 4, 'Vitamina', '10ml', 24, 8, DATE '2026-08-18', 'ENCERRADO', 'Suplementacao');
    P_INS_TRATAMENTO(9, 5, 5, 5, 'Vermifugo', '1 comprimido', 24, 5, DATE '2026-08-20', 'ATIVO', 'Administracao preventiva');
END;
/

-- FUNCOES
CREATE OR REPLACE FUNCTION F_JSON_ATENDIMENTO(
    P_ID_PRONTUARIO NUMBER,
    P_PET VARCHAR2,
    P_RESPONSAVEL VARCHAR2,
    P_VETERINARIO VARCHAR2,
    P_PROCEDIMENTO VARCHAR2
)
RETURN VARCHAR2
IS
    V_ID NUMBER;
BEGIN
    SELECT ID_PRONTUARIO INTO V_ID
    FROM PRONTUARIO
    WHERE ID_PRONTUARIO = P_ID_PRONTUARIO;

    IF P_PET IS NULL OR P_RESPONSAVEL IS NULL OR P_VETERINARIO IS NULL THEN
        RAISE VALUE_ERROR;
    END IF;

    RETURN '{"id_prontuario":' || V_ID ||
           ',"pet":"' || P_PET ||
           '","responsavel":"' || P_RESPONSAVEL ||
           '","veterinario":"' || P_VETERINARIO ||
           '","procedimento":"' || P_PROCEDIMENTO || '"}';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN '{"erro":"prontuario nao encontrado"}';
    WHEN VALUE_ERROR THEN
        RETURN '{"erro":"dados invalidos"}';
    WHEN OTHERS THEN
        RETURN '{"erro":"erro ao gerar JSON"}';
END F_JSON_ATENDIMENTO;
/

CREATE OR REPLACE FUNCTION F_FIM_TRATAMENTO(
    P_INICIO DATE,
    P_DURACAO NUMBER
)
RETURN DATE
IS
    V_DIAS NUMBER;
BEGIN
    IF P_INICIO IS NULL THEN
        RAISE VALUE_ERROR;
    END IF;

    IF P_DURACAO = 0 THEN
        RAISE ZERO_DIVIDE;
    END IF;

    IF P_DURACAO < 0 THEN
        RAISE VALUE_ERROR;
    END IF;

    V_DIAS := P_DURACAO;
    RETURN P_INICIO + V_DIAS;
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        RETURN NULL;
    WHEN VALUE_ERROR THEN
        RETURN NULL;
    WHEN OTHERS THEN
        RETURN NULL;
END F_FIM_TRATAMENTO;
/

-- PROCEDURES RELATORIO
CREATE OR REPLACE PROCEDURE P_RELATORIO_JSON
IS
    V_QTD NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_QTD FROM PRONTUARIO;

    IF V_QTD = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;

    FOR R IN (
        SELECT PR.ID_PRONTUARIO,
               P.NOME PET,
               R.NOME RESPONSAVEL,
               V.NOME VETERINARIO,
               PR.PROCEDIMENTO
        FROM PRONTUARIO PR
        JOIN PET P ON PR.ID_PET = P.ID_PET
        JOIN RESPONSAVEL R ON P.ID_RESP = R.ID_RESP
        JOIN MED_VET V ON PR.ID_MED_VET = V.ID_MED_VET
        ORDER BY P.NOME
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            F_JSON_ATENDIMENTO(
                R.ID_PRONTUARIO,
                R.PET,
                R.RESPONSAVEL,
                R.VETERINARIO,
                R.PROCEDIMENTO
            )
        );
    END LOOP;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_LOG_ERRO('P_RELATORIO_JSON', SQLCODE, 'NENHUM PRONTUARIO ENCONTRADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_RELATORIO_JSON', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_RELATORIO_JSON', SQLCODE, SQLERRM);
END P_RELATORIO_JSON;
/

CREATE OR REPLACE PROCEDURE P_RELATORIO_TRATAMENTOS
IS
    CURSOR C_TRATAMENTOS IS
        SELECT ID_PET, STATUS, DURACAO_DIAS
        FROM TRATAMENTO
        ORDER BY ID_PET, STATUS;

    V_ID_PET NUMBER;
    V_STATUS VARCHAR2(20);
    V_DURACAO NUMBER;

    V_PET_ATUAL NUMBER := NULL;
    V_STATUS_ATUAL VARCHAR2(20) := NULL;
    V_TOTAL_STATUS NUMBER := 0;
    V_TOTAL_PET NUMBER := 0;
    V_TOTAL NUMBER := 0;
    V_EXISTE NUMBER := 0;
BEGIN
    OPEN C_TRATAMENTOS;

    LOOP
        FETCH C_TRATAMENTOS INTO V_ID_PET, V_STATUS, V_DURACAO;
        EXIT WHEN C_TRATAMENTOS%NOTFOUND;

        V_EXISTE := 1;

        IF V_PET_ATUAL IS NULL THEN
            V_PET_ATUAL := V_ID_PET;
            V_STATUS_ATUAL := V_STATUS;
        END IF;

        IF V_ID_PET <> V_PET_ATUAL THEN
            DBMS_OUTPUT.PUT_LINE(
                '  ' || V_PET_ATUAL || '  | ' || V_STATUS_ATUAL || ' | ' || V_TOTAL_STATUS
            );
            DBMS_OUTPUT.PUT_LINE(
                '  ' || V_PET_ATUAL || ' T| ' || '     ' || ' | ' || V_TOTAL_PET
            );

            V_PET_ATUAL := V_ID_PET;
            V_STATUS_ATUAL := V_STATUS;
            V_TOTAL_STATUS := 0;
            V_TOTAL_PET := 0;
        ELSIF V_STATUS <> V_STATUS_ATUAL THEN
            DBMS_OUTPUT.PUT_LINE(
                '  ' || V_PET_ATUAL || '  | ' || V_STATUS_ATUAL || ' | ' || V_TOTAL_STATUS
            );

            V_STATUS_ATUAL := V_STATUS;
            V_TOTAL_STATUS := 0;
        END IF;

        V_TOTAL_STATUS := V_TOTAL_STATUS + V_DURACAO;
        V_TOTAL_PET := V_TOTAL_PET + V_DURACAO;
        V_TOTAL := V_TOTAL + V_DURACAO;
    END LOOP;

    CLOSE C_TRATAMENTOS;

    IF V_EXISTE = 0 THEN
        RAISE NO_DATA_FOUND;
    END IF;

    DBMS_OUTPUT.PUT_LINE(
        '  ' || V_PET_ATUAL || '  | ' || V_STATUS_ATUAL || ' | ' || V_TOTAL_STATUS
    );
    DBMS_OUTPUT.PUT_LINE(
        '  ' || V_PET_ATUAL || ' T| ' || '     ' || ' | ' || V_TOTAL_PET
    );
    DBMS_OUTPUT.PUT_LINE(
        'Total| ' || '     ' || ' | ' || V_TOTAL
    );
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        IF C_TRATAMENTOS%ISOPEN THEN
            CLOSE C_TRATAMENTOS;
        END IF;
        P_LOG_ERRO('P_RELATORIO_TRATAMENTOS', SQLCODE, 'NENHUM TRATAMENTO ENCONTRADO');
    WHEN VALUE_ERROR THEN
        IF C_TRATAMENTOS%ISOPEN THEN
            CLOSE C_TRATAMENTOS;
        END IF;
        P_LOG_ERRO('P_RELATORIO_TRATAMENTOS', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        IF C_TRATAMENTOS%ISOPEN THEN
            CLOSE C_TRATAMENTOS;
        END IF;
        P_LOG_ERRO('P_RELATORIO_TRATAMENTOS', SQLCODE, SQLERRM);
END P_RELATORIO_TRATAMENTOS;
/

-- TRIGGER
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PRONTUARIO
AFTER INSERT OR UPDATE OR DELETE ON PRONTUARIO
FOR EACH ROW
DECLARE
    V_ID NUMBER;
BEGIN
    SELECT NVL(MAX(ID_AUDITORIA), 0) + 1
    INTO V_ID
    FROM AUDITORIA_PRONTUARIO;

    IF INSERTING THEN
        INSERT INTO AUDITORIA_PRONTUARIO(
            ID_AUDITORIA, USUARIO_DB, OPERACAO, DATA_HORA,
            ID_PRONTUARIO_NOVO, ID_PET_NOVO, ID_MED_VET_NOVO, ID_CONSULTA_NOVO,
            PROCEDIMENTO_NOVO, DATA_PROCEDIMENTO_NOVO, LOCAL_NOVO
        )
        VALUES(
            V_ID, USER, 'INSERT', SYSDATE,
            :NEW.ID_PRONTUARIO, :NEW.ID_PET, :NEW.ID_MED_VET, :NEW.ID_CONSULTA,
            :NEW.PROCEDIMENTO, :NEW.DATA_PROCEDIMENTO, :NEW.LOCAL_ATENDIMENTO
        );
    ELSIF UPDATING THEN
        INSERT INTO AUDITORIA_PRONTUARIO(
            ID_AUDITORIA, USUARIO_DB, OPERACAO, DATA_HORA,
            ID_PRONTUARIO_ANTERIOR, ID_PET_ANTERIOR, ID_MED_VET_ANTERIOR, ID_CONSULTA_ANTERIOR,
            PROCEDIMENTO_ANTERIOR, DATA_PROCEDIMENTO_ANTERIOR, LOCAL_ANTERIOR,
            ID_PRONTUARIO_NOVO, ID_PET_NOVO, ID_MED_VET_NOVO, ID_CONSULTA_NOVO,
            PROCEDIMENTO_NOVO, DATA_PROCEDIMENTO_NOVO, LOCAL_NOVO
        )
        VALUES(
            V_ID, USER, 'UPDATE', SYSDATE,
            :OLD.ID_PRONTUARIO, :OLD.ID_PET, :OLD.ID_MED_VET, :OLD.ID_CONSULTA,
            :OLD.PROCEDIMENTO, :OLD.DATA_PROCEDIMENTO, :OLD.LOCAL_ATENDIMENTO,
            :NEW.ID_PRONTUARIO, :NEW.ID_PET, :NEW.ID_MED_VET, :NEW.ID_CONSULTA,
            :NEW.PROCEDIMENTO, :NEW.DATA_PROCEDIMENTO, :NEW.LOCAL_ATENDIMENTO
        );
    ELSE
        INSERT INTO AUDITORIA_PRONTUARIO(
            ID_AUDITORIA, USUARIO_DB, OPERACAO, DATA_HORA,
            ID_PRONTUARIO_ANTERIOR, ID_PET_ANTERIOR, ID_MED_VET_ANTERIOR, ID_CONSULTA_ANTERIOR,
            PROCEDIMENTO_ANTERIOR, DATA_PROCEDIMENTO_ANTERIOR, LOCAL_ANTERIOR
        )
        VALUES(
            V_ID, USER, 'DELETE', SYSDATE,
            :OLD.ID_PRONTUARIO, :OLD.ID_PET, :OLD.ID_MED_VET, :OLD.ID_CONSULTA,
            :OLD.PROCEDIMENTO, :OLD.DATA_PROCEDIMENTO, :OLD.LOCAL_ATENDIMENTO
        );
    END IF;
END;
/

-- TESTES
BEGIN
    P_RELATORIO_JSON;
END;
/

BEGIN
    P_RELATORIO_TRATAMENTOS;
END;
/

BEGIN
    P_INS_RESP(6, NULL, DATE '1990-01-01', '66666666666', 'teste1@gmail.com');
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    P_INS_RESP(7, NULL, DATE '1990-01-01', '77777777777', 'teste2@gmail.com');
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    P_INS_PET(6, 'Erro', NULL, 'SRD', 'CAO', DATE '2024-01-01', 999);
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    P_INS_CONSULTA(6, 999, 1, DATE '2026-09-01', 'Erro', 'AGENDADA', NULL);
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

BEGIN
    P_INS_TRATAMENTO(6, 999, 1, NULL, 'Erro', '1 comprimido', 12, 3, DATE '2026-09-01', 'ATIVO', NULL);
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

SELECT F_JSON_ATENDIMENTO(1, 'Pet Teste', 'Responsavel Teste', 'Veterinario Teste', 'Consulta veterinaria') FROM DUAL;
SELECT F_JSON_ATENDIMENTO(999, 'Pet', 'Responsavel', 'Veterinario', 'Consulta')FROM DUAL; -- Prontu�rio com ID inexistente

SELECT F_FIM_TRATAMENTO(DATE '2026-09-13', 7) FROM DUAL;
SELECT F_FIM_TRATAMENTO(DATE '2026-09-13', 0) FROM DUAL; -- 0 = valor inv�lido (Dura��o n�o pode ser 0)
SELECT F_FIM_TRATAMENTO(DATE '2026-09-13', -2) FROM DUAL; -- -2 = valor inv�lido (Dura��o n�o pode ser negativa)


BEGIN
    P_INS_PRONTUARIO(
        6, 1, 1, NULL, 'Teste auditoria',
        DATE '2026-08-21', 'Sala 1', 'Insercao para auditoria'
    );

    UPDATE PRONTUARIO
    SET OBSERVACAO = 'Atualizacao para auditoria'
    WHERE ID_PRONTUARIO = 6;

    DELETE FROM PRONTUARIO
    WHERE ID_PRONTUARIO = 6;
END;
/

SELECT
    ID_PET,
    NVL(LAG(NOME) OVER(ORDER BY ID_PET), 'VAZIO') ANTERIOR,
    NOME ATUAL,
    NVL(LEAD(NOME) OVER(ORDER BY ID_PET), 'VAZIO') PROXIMO
FROM PET;

BEGIN
    FOR R IN (
        SELECT V.NOME, COUNT(PR.ID_PRONTUARIO) TOTAL_ATENDIMENTOS
        FROM MED_VET V
        JOIN PRONTUARIO PR ON V.ID_MED_VET = PR.ID_MED_VET
        GROUP BY V.NOME
        ORDER BY TOTAL_ATENDIMENTOS DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.NOME || ' | ' || R.TOTAL_ATENDIMENTOS);
    END LOOP;
END;
/

BEGIN
    FOR R IN (
        SELECT R.NOME, COUNT(P.ID_PET) TOTAL_PETS
        FROM RESPONSAVEL R
        JOIN PET P ON R.ID_RESP = P.ID_RESP
        GROUP BY R.NOME
        ORDER BY TOTAL_PETS DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.NOME || ' | ' || R.TOTAL_PETS);
    END LOOP;
END;
/

SELECT * FROM LOG_ERRO ORDER BY ID_LOG;
SELECT * FROM AUDITORIA_PRONTUARIO ORDER BY ID_AUDITORIA;