/*
Equipe: OLLI PET

André Rosa Colombo - RM563112
Gabriely Bonfim Silva - RM566242
Henrique Rodrigues Vespasiano - RM562917
Mirelly Sousa Alves - RM566299
Ruan Luca Feliciano - RM562218
*/
SET SERVEROUTPUT ON
SET VERIFY OFF

-- DROPS
DROP TABLE PRONTUARIO CASCADE CONSTRAINTS;
DROP TABLE PET CASCADE CONSTRAINTS;
DROP TABLE VETERINARIO CASCADE CONSTRAINTS;
DROP TABLE RESPONSAVEL CASCADE CONSTRAINTS;
DROP TABLE LOG_ERRO CASCADE CONSTRAINTS;

-- TABELAS
CREATE TABLE LOG_ERRO(
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_PROCEDURE VARCHAR2(100),
    USUARIO_DB VARCHAR2(100),
    DATA_ERRO DATE,
    CODIGO_ERRO NUMBER,
    MSG_ERRO VARCHAR2(4000)
);

CREATE TABLE RESPONSAVEL(
    ID_RESP NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASC DATE,
    CPF VARCHAR2(14) UNIQUE,
    EMAIL VARCHAR2(100)
);

CREATE TABLE VETERINARIO(
    ID_VETERINARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CRMV VARCHAR2(20) UNIQUE,
    EMAIL VARCHAR2(100)
);

CREATE TABLE PET(
    ID_PET NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    DESCRICAO VARCHAR2(200),
    RACA VARCHAR2(100),
    DATA_NASC DATE,
    ID_RESP NUMBER NOT NULL,
    CONSTRAINT FK_RESP FOREIGN KEY(ID_RESP) REFERENCES RESPONSAVEL(ID_RESP)
);

CREATE TABLE PRONTUARIO(
    ID_PRONTUARIO NUMBER PRIMARY KEY,
    ID_PET NUMBER NOT NULL,
    PROCEDIMENTO VARCHAR2(200),
    DATA_PROCEDIMENTO DATE,
    LOCAL_ATENDIMENTO VARCHAR2(100),
    ID_VETERINARIO NUMBER NOT NULL,
    CONSTRAINT FK_PET FOREIGN KEY(ID_PET) REFERENCES PET(ID_PET),
    CONSTRAINT FK_VET FOREIGN KEY(ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);

-- PROCEDURES

CREATE OR REPLACE PROCEDURE P_LOG_ERRO(
    P_NOME_PROC VARCHAR2,
    P_COD NUMBER,
    P_MSG VARCHAR2
)
IS
BEGIN
    INSERT INTO LOG_ERRO
    (NOME_PROCEDURE, USUARIO_DB, DATA_ERRO, CODIGO_ERRO, MSG_ERRO)
    VALUES (P_NOME_PROC, USER, SYSDATE, P_COD, P_MSG);
END;

CREATE OR REPLACE PROCEDURE P_INS_RESP(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_DATA DATE,
    P_CPF VARCHAR2,
    P_EMAIL VARCHAR2
)
IS
BEGIN
    INSERT INTO RESPONSAVEL VALUES(P_ID, P_NOME, P_DATA, P_CPF, P_EMAIL);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, 'CPF DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_RESP', SQLCODE, SQLERRM);
END;

CREATE OR REPLACE PROCEDURE P_INS_VET(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_CRMV VARCHAR2,
    P_EMAIL VARCHAR2
)
IS
BEGIN
    INSERT INTO VETERINARIO VALUES(P_ID, P_NOME, P_CRMV, P_EMAIL);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, 'CRMV DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_VET', SQLCODE, SQLERRM);
END;

CREATE OR REPLACE PROCEDURE P_INS_PET(
    P_ID NUMBER,
    P_NOME VARCHAR2,
    P_DESC VARCHAR2,
    P_RACA VARCHAR2,
    P_DATA DATE,
    P_RESP NUMBER
)
IS
BEGIN
    INSERT INTO PET VALUES(P_ID, P_NOME, P_DESC, P_RACA, P_DATA, P_RESP);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, 'PET DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_PET', SQLCODE, SQLERRM);
END;

CREATE OR REPLACE PROCEDURE P_INS_PRONTUARIO(
    P_ID NUMBER,
    P_IDPET NUMBER,
    P_PROC VARCHAR2,
    P_DATA DATE,
    P_LOCAL VARCHAR2,
    P_VET NUMBER
)
IS
BEGIN
    INSERT INTO PRONTUARIO VALUES(P_ID, P_IDPET, P_PROC, P_DATA, P_LOCAL, P_VET);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, 'PRONTUARIO DUPLICADO');
    WHEN VALUE_ERROR THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, 'ERRO DE VALOR');
    WHEN OTHERS THEN
        P_LOG_ERRO('P_INS_PRONTUARIO', SQLCODE, SQLERRM);
END;

-- CARGA
BEGIN
    P_INS_RESP(1,'Carlos Silva',DATE '1985-05-10','11111111111','carlos@gmail.com');
    P_INS_RESP(2,'Mariana Souza',DATE '1990-08-15','22222222222','mariana@gmail.com');
END;

BEGIN
    P_INS_VET(1,'Dr Joao','CRMV001','joao@pet.com');
    P_INS_VET(2,'Dra Ana','CRMV002','ana@pet.com');
END;

BEGIN
    P_INS_PET(1,'Rex','Agitado','Labrador',DATE '2020-01-10',1);
    P_INS_PET(2,'Mia','Calma','Siames',DATE '2021-03-15',2);
END;

BEGIN
    P_INS_PRONTUARIO(1,1,'Vacina',SYSDATE,'Sala 1',1);
    P_INS_PRONTUARIO(2,2,'Consulta',SYSDATE,'Sala 2',2);
END;

-- JOINS COM GROUP BY
BEGIN
    FOR R IN (
        SELECT V.NOME, COUNT(PR.ID_PET) TOTAL
        FROM VETERINARIO V
        JOIN PRONTUARIO PR ON V.ID_VETERINARIO = PR.ID_VETERINARIO
        GROUP BY V.NOME
        ORDER BY TOTAL DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('MEDICO: '||R.NOME||' TOTAL: '||R.TOTAL);
    END LOOP;
END;

BEGIN
    FOR R IN (
        SELECT R.NOME, COUNT(P.ID_PET) TOTAL
        FROM RESPONSAVEL R
        JOIN PET P ON R.ID_RESP = P.ID_RESP
        GROUP BY R.NOME
        ORDER BY TOTAL DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('RESP: '||R.NOME||' PETS: '||R.TOTAL);
    END LOOP;
END;

BEGIN
    FOR R IN (
        SELECT P.NOME PET, V.NOME MEDICO, PR.PROCEDIMENTO
        FROM PRONTUARIO PR
        JOIN PET P ON PR.ID_PET = P.ID_PET
        JOIN VETERINARIO V ON PR.ID_VETERINARIO = V.ID_VETERINARIO
        ORDER BY P.NOME
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(R.PET||' - '||R.MEDICO||' - '||R.PROCEDIMENTO);
    END LOOP;
END;

-- LAG/LEAD
SELECT
    ID_PET,
    NVL(LAG(NOME) OVER(ORDER BY ID_PET),'VAZIO') ANTERIOR,
    NOME ATUAL,
    NVL(LEAD(NOME) OVER(ORDER BY ID_PET),'VAZIO') PROXIMO
FROM PET;

-- CURSORES
DECLARE
    CURSOR C_PETS IS SELECT NOME, RACA FROM PET;
    V_NOME PET.NOME%TYPE;
    V_RACA PET.RACA%TYPE;
BEGIN
    OPEN C_PETS;
    LOOP
        FETCH C_PETS INTO V_NOME, V_RACA;
        EXIT WHEN C_PETS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('PET: '||V_NOME||' | '||V_RACA);
    END LOOP;
    CLOSE C_PETS;
END;

DECLARE
    CURSOR C_MED IS SELECT NOME FROM VETERINARIO;
    V_NOME VARCHAR2(100);
BEGIN
    OPEN C_MED;
    LOOP
        FETCH C_MED INTO V_NOME;
        EXIT WHEN C_MED%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('MEDICO: '||V_NOME);
    END LOOP;
    CLOSE C_MED;
END;

DECLARE
    CURSOR C_PRONT IS SELECT PROCEDIMENTO FROM PRONTUARIO;
    V_PROC VARCHAR2(100);
BEGIN
    OPEN C_PRONT;
    LOOP
        FETCH C_PRONT INTO V_PROC;
        EXIT WHEN C_PRONT%NOTFOUND;
        IF V_PROC = 'Vacina' THEN
            DBMS_OUTPUT.PUT_LINE('PREVENTIVO');
        ELSE
            DBMS_OUTPUT.PUT_LINE('OUTRO');
        END IF;
    END LOOP;
    CLOSE C_PRONT;
END;

-- RELATÓRIO FINAL
DECLARE
    CURSOR C_SUM IS
        SELECT V.NOME, COUNT(*) TOTAL
        FROM PRONTUARIO PR
        JOIN VETERINARIO V ON PR.ID_VETERINARIO = V.ID_VETERINARIO
        GROUP BY V.NOME;

    V_NOME VARCHAR2(100);
    V_TOTAL NUMBER;
BEGIN
    OPEN C_SUM;
    LOOP
        FETCH C_SUM INTO V_NOME, V_TOTAL;
        EXIT WHEN C_SUM%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('MEDICO: '||V_NOME||' TOTAL ATEND: '||V_TOTAL);
    END LOOP;
    CLOSE C_SUM;
END;

-- LOG
SELECT * FROM LOG_ERRO;